CREATE TABLE PERSONAS
(COD_HOSPITAL INTEGER,
DNI INTEGER,
APELLIDOS VARCHAR(50),
FUNCION VARCHAR(30),
SALARIO INTEGER,
LOCALIDAD VARCHAR(20));

INSERT INTO PERSONAS VALUES(1, 12345678, 'Garcia Hernandez, Eladio', 'CONSERJE', 1200, 'LORCA');

INSERT INTO PERSONAS VALUES(1, 87654321, 'Fuentes Bermejo, Carlos', 'DIRECTOR', 2000, 'MURCIA');

INSERT INTO PERSONAS VALUES(2, 55544433, 'Gonzalez Marin, Alicia', 'CONSERJE', 1200, 'MURCIA');

INSERT INTO PERSONAS VALUES(1, 66655544, 'Castillo Montes, Pedro', 'MEDICO', 1700, 'MURCIA');

INSERT INTO PERSONAS VALUES(2, 22233322, 'Tristan Garcia, Ana', 'MEDICO', 1900, 'MURCIA');

INSERT INTO PERSONAS VALUES(3, 55544411, 'Ruiz Hernandez, Caridad', 'MEDICO', 1900, 'LORCA');

INSERT INTO PERSONAS VALUES(3, 99988333, 'Serrano Diaz, Alejandro', 'DIRECTOR', 2400, 'CARTAGENA');

INSERT INTO PERSONAS VALUES(4, 33222111, 'Mesa del Castilo, Juan', 'MEDICO', 2200, 'LORCA');

INSERT INTO PERSONAS VALUES(2, 22233333, 'Martinez Molina, Andres', 'MEDICO', 1600, 'CARTAGENA');

INSERT INTO PERSONAS VALUES(4, 55544412, 'Jimenez Jimenez, Dolores', 'CONSERJE', 1200, 'MURCIA');

INSERT INTO PERSONAS VALUES(4, 22233311, 'Martinez Molina, Gloria', 'MEDICO', 1600, 'MURCIA');

SELECT *
FROM PERSONAS;

SELECT DNI, APELLIDOS, FUNCION
FROM PERSONAS;

SELECT APELLIDOS
FROM PERSONAS
WHERE LOCALIDAD LIKE 'LORCA';

SELECT APELLIDOS
FROM PERSONAS
WHERE LOCALIDAD LIKE 'LORCA' OR LOCALIDAD LIKE 'MURCIA';

SELECT *
FROM PERSONAS
WHERE LOCALIDAD LIKE 'MURCIA' AND SALARIO > 1500;

SELECT *
FROM PERSONAS
WHERE LOCALIDAD LIKE 'MURCIA' AND SALARIO > 1500 AND FUNCION LIKE 'DIRECTOR';

SELECT *
FROM PERSONAS
WHERE FUNCION LIKE 'MEDICO'
ORDER BY APELLIDOS DESC;

SELECT DISTINCT LOCALIDAD
FROM PERSONAS;

SELECT *
FROM PERSONAS
WHERE SALARIO > 1500 AND FUNCION LIKE 'MEDICO'
ORDER BY SALARIO DESC;

SELECT *
FROM PERSONAS
WHERE APELLIDOS LIKE 'M%';

SELECT *
FROM PERSONAS
WHERE (APELLIDOS LIKE 'M%' OR APELLIDOS LIKE '%M%' OR APELLIDOS LIKE '%M' OR APELLIDOS LIKE 'm%' OR APELLIDOS LIKE '%m%' OR APELLIDOS LIKE '%m') AND FUNCION LIKE 'CONSERJE';

SELECT *
FROM PERSONAS
WHERE SALARIO BETWEEN 1500 AND 2000;

SELECT *
FROM PERSONAS
WHERE FUNCION IN ('MEDICO', 'DIRECTOR');

SELECT *
FROM PERSONAS
WHERE FUNCION NOT IN ('CONSERJE') AND SALARIO > 1500
ORDER BY APELLIDOS DESC;

SELECT *
FROM PERSONAS
WHERE LOCALIDAD IN ('MURCIA', 'CARTAGENA') AND COD_HOSPITAL LIKE 1;

SELECT *
FROM PERSONAS
WHERE COD_HOSPITAL IN (1, 2) AND SALARIO > 1500;

SELECT *
FROM PERSONAS
WHERE COD_HOSPITAL NOT LIKE 2 AND LOCALIDAD LIKE 'MURCIA';
