CREATE TABLE CLIENTES
(NIF CHAR(9) PRIMARY KEY,
NOMBRE VARCHAR(20) NOT NULL,
DIRECCION VARCHAR(50),
TELEFONO VARCHAR(20));

CREATE TABLE COCHES
(MATRICULA CHAR(8) PRIMARY KEY,
MARCA VARCHAR(20),
MODELO VARCHAR(20),
COLOR VARCHAR(20),
PRECIO DECIMAL(10,2),
NIF_CLIENTE CHAR(9));

CREATE TABLE REVISIONES
(CODIGO INTEGER PRIMARY KEY,
MATRICULA_COCHE CHAR(8),
FILTRO BOOLEAN DEFAULT FALSE,
ACEITE BOOLEAN DEFAULT FALSE,
FRENOS BOOLEAN DEFAULT FALSE);

ALTER TABLE COCHES
ADD FOREIGN KEY (NIF_CLIENTE) REFERENCES CLIENTES (NIF);

ALTER TABLE REVISIONES
ADD FOREIGN KEY (MATRICULA_COCHE) REFERENCES COCHES (MATRICULA);

INSERT INTO CLIENTES VALUES('111', 'Ignacio', 'Murcia', '555-11-22-33');

INSERT INTO CLIENTES VALUES('222', 'Julia', 'Burgos', '555-00-33-44');

INSERT INTO CLIENTES VALUES('333', 'Pedro', 'Cadiz', '555-99-88-00');

INSERT INTO CLIENTES VALUES('444', 'David', 'Vizcaya', '555-00-88-77');

INSERT INTO COCHES VALUES('2222-BBB', 'seat', 'ibiza', 'blanco', 12000, '111');

INSERT INTO COCHES VALUES('3333-CCC', 'seat', 'toledo', 'gris', 18000, '222');

INSERT INTO COCHES VALUES('4444-DDD', 'renault', 'clio', 'rojo', 15000, '222');

INSERT INTO COCHES VALUES('6666-FFF', 'renault', 'megane', 'blanco', 19000, '444');

INSERT INTO REVISIONES VALUES(1, '2222-BBB', TRUE, FALSE, TRUE);

INSERT INTO REVISIONES VALUES(2, '3333-CCC', TRUE, TRUE, TRUE);

INSERT INTO REVISIONES VALUES(3, '4444-DDD', FALSE, FALSE, TRUE);

INSERT INTO REVISIONES VALUES(4, '2222-BBB', TRUE, FALSE, TRUE);

SELECT NOMBRE
FROM CLIENTES
WHERE DIRECCION LIKE 'Murcia';

SELECT MODELO
FROM COCHES
WHERE MARCA LIKE 'seat';

SELECT MARCA, MODELO
FROM COCHES
WHERE NIF_CLIENTE LIKE '222';

SELECT NOMBRE, MATRICULA
FROM CLIENTES, COCHES
WHERE CLIENTES.NIF=COCHES.NIF_CLIENTE AND MATRICULA NOT IN (SELECT MATRICULA_COCHE FROM REVISIONES);

SELECT MATRICULA_COCHE
FROM REVISIONES
WHERE FILTRO LIKE TRUE;

SELECT MATRICULA_COCHE
FROM REVISIONES
WHERE FILTRO LIKE TRUE AND ACEITE LIKE TRUE AND FRENOS LIKE TRUE;

SELECT MATRICULA
FROM COCHES
WHERE COLOR LIKE 'blanco';

SELECT MARCA, MODELO
FROM COCHES
WHERE PRECIO > 15000;

SELECT NOMBRE
FROM CLIENTES
WHERE TELEFONO LIKE '%44';

SELECT DIRECCION
FROM CLIENTES
WHERE NIF LIKE '333';
